<?php
// Sample 05 — Typed Secrets (bella secrets generate php)
//
// secrets.php is generated by: bella secrets generate php --app php-05-typed-secrets
// It contains typed accessors — no raw getenv() calls in your app code.
//
// Run with:
//   bella exec --app php-05-typed-secrets -- php app.php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/secrets.php';

$s = new AppSecrets();

// Print all 8 secrets in KEY=value format (used by test-samples.sh for validation)
// Types are enforced by the generated class — port() is int, enableFeatures() is bool, etc.
echo 'PORT='                        . $s->port()                      . PHP_EOL;
echo 'DATABASE_URL='                . $s->databaseUrl()               . PHP_EOL;
echo 'EXTERNAL_API_KEY='            . $s->externalApiKey()            . PHP_EOL;
echo 'GLEAP_API_KEY='               . $s->gleapApiKey()               . PHP_EOL;
echo 'ENABLE_FEATURES='             . ($s->enableFeatures() ? 'true' : 'false') . PHP_EOL;
echo 'APP_ID='                      . $s->appId()                     . PHP_EOL;
echo 'ConnectionStrings__Postgres=' . $s->connectionstringsPostgres() . PHP_EOL;
echo 'APP_CONFIG='                  . $s->appConfig()                 . PHP_EOL;
