<?php
// auto-generated by: bella secrets generate php
// project: awesome/dev
// generated: 2026-03-14 00:00:00 UTC
// DO NOT edit manually — re-run bella secrets generate php to update.

declare(strict_types=1);

final class AppSecrets
{
    private static function require(string $key): string
    {
        $v = getenv($key);
        if ($v === false) throw new \RuntimeException("Required env var '$key' is not set.");
        return $v;
    }

    /** HTTP server port */
    public function port(): int { return (int) self::require("PORT"); }

    /** PostgreSQL connection string */
    public function databaseUrl(): string { return self::require("DATABASE_URL"); }

    /** Third-party API key */
    public function externalApiKey(): string { return self::require("EXTERNAL_API_KEY"); }

    /** Gleap service key */
    public function gleapApiKey(): string { return self::require("GLEAP_API_KEY"); }

    /** Feature flag */
    public function enableFeatures(): bool { return self::require("ENABLE_FEATURES") === "true"; }

    /** Application UUID */
    public function appId(): string { return self::require("APP_ID") /* UUID */; }

    /** Postgres connection string */
    public function connectionstringsPostgres(): string { return self::require("ConnectionStrings__Postgres"); }

    /** JSON app configuration */
    public function appConfig(): string { return self::require("APP_CONFIG"); }
}
