services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Bella/BellaBundle.php'

    App\Controller\SecretsController:
        tags: ['controller.service_arguments']

    BellaBaxter\BaxterClientOptions:
        arguments:
            $baxterUrl: '%env(resolve:BELLA_BAXTER_URL)%'
            $apiKey:    '%env(resolve:BELLA_BAXTER_API_KEY)%'

    BellaBaxter\BaxterClient:
        arguments:
            $options: '@BellaBaxter\BaxterClientOptions'
